# Generated by Django 2.0.6 on 2018-09-02 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0002_auto_20180902_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
