# Generated by Django 2.0.6 on 2018-09-02 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0003_auto_20180902_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_problem',
            name='comment_added_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
